##
# Full text search query for RDF4J with a Lucene SAIL.
##

PREFIX :<http://www.openrdf.org/contrib/lucenesail#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX dc: <http://purl.org/dc/terms/>

SELECT DISTINCT ?entity ?label ?vocabularyUri ?draft ?type ?snippetField ?snippetText ?score WHERE {
     ?search :query ?wildCardSearchString;
            :snippet ?snippetText ;
            :score ?score;
            :snippet ?snippetField .

    ?entity :matches ?search ;
            a ?type .
    {
        ?entity rdfs:label ?label .
    } UNION {
        ?entity dc:title ?label .
    }

    OPTIONAL {
        ?entity ?inVocabulary ?vocabularyUri .
    }
    OPTIONAL {
        ?entity ?isDraft ?draft .
    }
    FILTER (?type = ?term || ?type = ?vocabulary)
    FILTER (lang(?label) = ?langTag)
    BIND(?wildCardSearchString as ?temp)
}
ORDER BY desc(?score)
