PREFIX dd:   <http://onto.fel.cvut.cz/ontologies/data-description/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

# Replaces any occurrence of ?originalIri with ?newIri
# Prevents snapshot modification except rewiring the is-version-of relations
#   to maintain the link to the snapshotted entity
# Prevents identifier change record modification

DELETE {
    GRAPH ?graph {
        ?subject ?predicate ?object .
    }
}
INSERT {
    GRAPH ?graph {
        ?newSubject ?newPredicate ?newObject .
    }
}
WHERE {
    GRAPH ?graph {
        ?subject ?predicate ?object .
    }

    # only triples where the original IRI is used
    FILTER (
        ?subject = ?originalIri ||
        ?predicate = ?originalIri ||
        ?object = ?originalIri
    )

    FILTER (
        # Prevent snapshot modification
        # ?graph must not be a version of vocabulary
        NOT EXISTS { GRAPH ?graph { ?graph a dd:version-of-vocabulary } }
        ||
        # Unless rewiring the is-version-of-* relation
        # ?graph can be version of vocabulary if ?predicate is version-of-*
        (?predicate IN (dd:is-version-of-vocabulary, dd:is-version-of-term) && (?subject != ?originalIri))
    )

    # Prevent identifier change records modification
    FILTER NOT EXISTS {
        ?subject a <http://onto.fel.cvut.cz/ontologies/application/termit/identifier-change> .
    }

    # bind new values replacing the original IRI
    BIND(
        IF(?subject = ?originalIri,
            ?newIri,
            ?subject)
    AS ?newSubject
    )

    BIND(
        IF(?predicate = ?originalIri,
            ?newIri,
            ?predicate)
    AS ?newPredicate
    )

    BIND(
        IF(?object = ?originalIri,
            ?newIri,
            ?object)
    AS ?newObject
    )


}
