PREFIX dd: <http://onto.fel.cvut.cz/ontologies/data-description/>

SELECT (COUNT(DISTINCT ?asset) AS ?count) {
    ?asset a ?assetType .
    FILTER NOT EXISTS {
        ?asset a dd:object-version .
    }
}
