PREFIX pdp: <http://onto.fel.cvut.cz/ontologies/slovník/agendový/popis-dat/pojem/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX termit: <http://onto.fel.cvut.cz/ontologies/application/termit/pojem/>
PREFIX dc: <http://purl.org/dc/terms/>

SELECT ?slovnik ?labelSlovniku ( COUNT(DISTINCT ?pojem) AS ?count ) {
    GRAPH ?g {
        ?pojem a skos:Concept ;
    }
    ?pojem pdp:je-pojmem-ze-slovníku ?slovnik .
    FILTER NOT EXISTS {
        ?slovnik a pdp:verze-slovníku .
    }
    ?slovnik dc:title ?labelSlovniku .
} GROUP BY ?slovnik ?labelSlovniku
