PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX dc: <http://purl.org/dc/terms/>
PREFIX dd: <http://onto.fel.cvut.cz/ontologies/data-description/>

SELECT ?vocabulary ?label ( COUNT(DISTINCT ?term) AS ?count ) ?language {
    GRAPH ?g {
        ?term a skos:Concept ;
            skos:inScheme ?vocabulary .
        ?vocabulary dc:title ?label ;
            dc:language ?language .
    }
    FILTER NOT EXISTS {
        ?vocabulary a dd:vocabulary-version .
    }
} GROUP BY ?vocabulary ?label ?language
