PREFIX pdp: <http://onto.fel.cvut.cz/ontologies/slovník/agendový/popis-dat/pojem/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX termit: <http://onto.fel.cvut.cz/ontologies/application/termit/pojem/>
PREFIX dc: <http://purl.org/dc/terms/>

SELECT ?vocabulary ?label ( COUNT(DISTINCT ?term) AS ?count ) ?language {
    GRAPH ?g {
        ?term a skos:Concept ;
    }
    ?term pdp:je-pojmem-ze-slovníku ?vocabulary .
    FILTER NOT EXISTS {
        ?vocabulary a pdp:verze-slovníku .
    }
    ?vocabulary dc:title ?label .
    ?vocabulary dc:language ?language .
} GROUP BY ?vocabulary ?label ?language
