PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX pdp: <http://onto.fel.cvut.cz/ontologies/slovník/agendový/popis-dat/pojem/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX dc: <http://purl.org/dc/terms/>
PREFIX vann: <http://purl.org/vocab/vann/>

CONSTRUCT {
    ?vocabulary a owl:Ontology ;
              a skos:ConceptScheme ;
              dc:language ?language ;
              dc:title ?label ;
              dc:description ?description ;
              dc:creator ?fullName ;
              dc:created ?created ;
              dc:rights ?rights ;
              owl:imports ?imported ;
              owl:versionIRI ?versionIri ;
              vann:preferredNamespaceUri ?nsUri ;
              vann:preferredNamespacePrefix ?nsPrefix ;
              <http://purl.org/ontology/bibo/status> ?status ;
              ?y ?z .
} WHERE {
    GRAPH ?g {
        ?vocabulary dc:title ?label ;
            dc:language ?language .
        OPTIONAL {
            ?vocabulary dc:description ?description .
        }
        OPTIONAL {
            ?vocabulary owl:versionIRI ?versionIri .
        }
        OPTIONAL {
            ?vocabulary dc:rights ?rights .
        }
        OPTIONAL {
            ?vocabulary <http://purl.org/vocab/vann/preferredNamespaceUri> ?nsUri ;
                      <http://purl.org/vocab/vann/preferredNamespacePrefix> ?nsPrefix .
        }
        OPTIONAL {
            ?vocabulary <http://purl.org/ontology/bibo/status> ?status .
        }
        OPTIONAL {
            ?vocabulary ?y ?z .
            FILTER EXISTS {
                    ?y a <http://onto.fel.cvut.cz/ontologies/application/termit/pojem/vlastní-atribut> .
                }
        }
    }
    OPTIONAL {
        ?vocabulary pdp:importuje-slovník ?imported .
    }
    OPTIONAL {
        ?createRecord a pdp:vytvoření-entity ;
            pdp:má-změněnou-entitu ?vocabulary ;
            pdp:má-editora ?author ;
            pdp:má-datum-a-čas-modifikace ?created .
        ?author pdp:má-křestní-jméno ?firstName ;
            pdp:má-příjmení ?lastName .
        {
          SELECT (max(?createdDate) AS ?createdDateMax) ?vocabulary
          WHERE {   ?createRecord a pdp:vytvoření-entity ;
                    pdp:má-změněnou-entitu ?vocabulary ;
                    pdp:má-datum-a-čas-modifikace ?createdDate . } GROUP BY ?vocabulary
        }
        FILTER(?createdDateMax = ?created)
    }
    BIND (CONCAT(?firstName, " ", ?lastName) AS ?fullName)
}
