PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX pdp: <http://onto.fel.cvut.cz/ontologies/slovník/agendový/popis-dat/pojem/>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

CONSTRUCT {
    ?term a ?type ;
          skos:broader ?superClass ;
          skos:broader ?whole ;
          skos:broader ?parentEvent .
} WHERE {
    GRAPH ?g {
        ?term skos:inScheme ?vocabulary .
        ?term a ?type .
        OPTIONAL {
            ?term rdfs:subClassOf ?superClass .
            FILTER (!sameTerm(?term, ?superClass))
            FILTER (!STRSTARTS(STR(?superClass), str(owl:)))
        }
    }
    OPTIONAL {
        ?whole <http://onto.fel.cvut.cz/ontologies/ufo/has-part> ?term .
    }
    OPTIONAL {
        ?parentEvent <http://onto.fel.cvut.cz/ontologies/ufo/has-participant> ?term .
    }
}
